<?php

include_once __DIR__."/../Module/AdslotModule.php";

class AdslotController extends AdslotModule
{
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @param $data
     * @return false
     */
    public function addEmployee($data){
        return parent::addEmployee($data);
    }

    /**
     * @param $title
     * @return bool
     */
    public function checkEmployee($title){
         $sql = parent::checkEmployee($title);

        return ($sql) && $sql->num_rows > 0;
    }

    /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get($id = '',$limit = ''){
        $sql = parent::get($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }
    /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_attendency_by_today($id = '',$limit = ''){
        $sql = parent::get_attendency_by_today($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }  /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_by_EmployeeAtt($id = '',$limit = ''){
        $sql = parent::get_by_EmployeeAtt($id,$limit);
        $data = false;

        if($sql->num_rows > 0){
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);
                print_r($data);
        }

        
        return $data;
    }
    /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_inEmployee($id = '',$limit = ''){
        $sql = parent::get_inEmployee($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }
 /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_employee_Profile($id = '',$limit = ''){
        $sql = parent::get_employee_Profile($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }


     /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_attendency_by_groupMonth($id = '',$limit = ''){
        $sql = parent::get_attendency_by_groupMonth($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }



     /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_employeeProfile($id = '',$limit = ''){
        $sql = parent::get_employeeProfile($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }


    /**
     * @param $user
     * @param string $limit
     * @return mixed
     */
    public function get_groupedData($user,$limit = '')
    {
        $sql = parent::get_groupedData($user, $limit); // TODO: Change the autogenerated stub

        $data = false;

        if($sql->num_rows > 0)
            $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }


    

    /**
     * @param $data
     * @return false|mixed
     */
    public function update($data)
    {
        return parent::update($data);
    }

    /**
     * @param $id
     * @param $user_id
     * @return bool
     */
    public function deleteEmployee($id, $user_id)
    {
        return (parent::deleteEmployee($id,$user_id));
    }





    ////Mwananch ASSiament

     /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_displayRate($id = '',$limit = ''){
        $sql = parent::get_displayRate($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }
      /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_displayRate_by_pid($id = '',$limit = ''){
        $sql = parent::get_displayRate_by_pid($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    } 


       /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_sponser_content($id = '',$limit = ''){
        $sql = parent::get_sponser_content($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

       /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_social_medias($id = '',$limit = ''){
        $sql = parent::get_social_medias($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }       /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_vedeo_production($id = '',$limit = ''){
        $sql = parent::get_vedeo_production($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

}