<?php

include_once __DIR__."/../Module/EdepartmentModule.php";

class EdepartmentController extends EdepartmentModule
{
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @param $data
     * @return false
     */
    public function add_Edepartment($data){
        return parent::add_Edepartment($data);
    }

    /**
     * @param $title
     * @return bool
     */
    public function check_Edepartment($title){
         $sql = parent::check_Edepartment($title);

        return ($sql) && $sql->num_rows > 0;
    }

    /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_Edepartment($id = '',$limit = ''){
        $sql = parent::get_Edepartment($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }


      /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get($id = '',$limit = ''){
        $sql = parent::get($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

    /**
     * @param $user
     * @param string $limit
     * @return mixed
     */
    public function get_by_Edepartment($user,$limit = '')
    {
        $sql = parent::get_by_Edepartment($user, $limit); // TODO: Change the autogenerated stub

        $data = false;

        if($sql->num_rows > 0)
            $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

    /**
     * @param $data
     * @return false|mixed
     */
    public function update_Edepartment($data)
    {
        return parent::update_Edepartment($data);
    }

    /**
     * @param $id
     * @param $user_id
     * @return bool
     */
    public function delete_Edepartment($id, $user_id)
    {
        return (parent::delete_Edepartment($id,$user_id)->num_rows > 0);
    }

}