<?php

include_once __DIR__."/../Module/EmployeeAttendencyModule.php";

class EmployeeAttendencyController extends EmployeeAttendencyModule
{
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @param $data
     * @return false
     */
    public function add_empAttndcy($data){
        return parent::add_empAttndcy($data);
    }

    /**
     * @param $title
     * @return bool
     */
    public function check_empAttndcy($title){
         $sql = parent::check_empAttndcy($title);

        return ($sql) && $sql->num_rows > 0;
    }

    /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function get_empAttndcy($id = '',$limit = ''){
        $sql = parent::get_empAttndcy($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

    /**
     * @param $user
     * @param string $limit
     * @return mixed
     */
    public function get_by_empAttndcy($user,$limit = '')
    {
        $sql = parent::get_by_empAttndcy($user, $limit); // TODO: Change the autogenerated stub

        $data = false;

        if($sql->num_rows > 0)
            $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

    /**
     * @param $data
     * @return false|mixed
     */
    public function update_empAttndcy($data)
    {
        return parent::update_empAttndcy($data);
    }

    /**
     * @param $id
     * @param $user_id
     * @return bool
     */
    public function delete_empAttnd($id, $user_id)
    {
        return (parent::delete_empAttndcy($id,$user_id));
    }

}