<?php

include_once __DIR__."/../Module/NotificationModule.php";

include_once __DIR__."/../HTTP/http.php";

class NotificationController extends NotificationModule
{


private $apiUrl, $apiKey;

    /**
     * NotificationController constructor.
     */
    public function __construct()
    {
        parent::__construct();

        $this->apiUrl = getenv("apiUrl");
        $this->apiKey = getenv("apiKey");
    }

    /**
     * @param $data
     * @return false|mixed
     */
    public function add($data)
    {
        return parent::add($data); // TODO: Change the autogenerated stub
    }

    public function send_notification($data){
        $data = parent::decode($data);
        http::http($this->apiUrl,["to"=>$data->to, 'notification'=>$data->body,"data"=>$data->data],
            ["Authorization"=>"key=$this->apiKey","Content-Type"=>"application/json","cache-control"=>"no-cache"]);
    }

    /**
     * @param string $limit
     * @return array
     */
    public function get($limit = ''){
        $user = parent::get($limit);
        $data = false;

        if($user->num_rows > 0)
            $data = $user->fetch_all(MYSQLI_ASSOC);

        return $data;
    }
}