<?php
include_once __DIR__ . '/../module/PaymentModal.php';

class PaymentController extends PaymentModal
{
    public function __construct()
    {
        parent::__construct();
    }

    public function add($obj)
    {
        return parent::add($obj); // TODO: Change the autogenerated stub
    }

    public function updatePayment($obj){
        return parent::updatePayment($obj);
    }

    public function get($id='')
    {
        $dat = parent::get($id); // TODO: Change the autogenerated stub
		$data = false;
        if($dat && $dat->num_rows > 0){
			
			if(!empty($id))
				$data = $dat->fetch_object();
			else
               $data = $dat->fetch_all(MYSQLI_ASSOC);
        }

        return $data;
    }

    public function exist($user,$token)
    {
        $sql = parent::exist($user, $token); // TODO: Change the autogenerated stub

        return  $sql && $sql->num_rows > 0;
    }


    /**
     * Compute the signature and return the digest
     *
     * @param array $parameters
     * @param string $signed_fields
     * @param string $api_secret
     * @return string  HMAC SHA256 or RSA signature of data in the format
     */
    public function computeSignature($parameters, $signed_fields, $api_secret){

        $fields_order = explode(',', $signed_fields);
        $sign_data = "";
        foreach ($fields_order as $key) {
            $key_arr = explode(".", $key);
//            $tkey = "";
            if(count($key_arr)==1)
            {
                $sign_data .= "&$key=".$parameters[$key];
            }else if(count($key_arr)==2){
//                $tkey = $key_arr[0].".".$key_arr[1];
                $sign_data .= "&$key=".$parameters[$key_arr[0]][$key_arr[1]];
            }else{
                throw Exception("Request dimention not supported");
            }

        }

        //$sign_data.="#";
        //echo $api_secret;
        $sign_data = ltrim($sign_data,'&');
        return hash_hmac('sha256', $sign_data, $api_secret,false);
    }



}