<?php

include_once __DIR__."/../Module/PostModule.php";

class PostController extends PostModule
{
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @param $data
     * @return false
     */
    public function addPost($data){
        return parent::addPost($data);
    }

    /**
     * @param $title
     * @return bool
     */
    public function checkPost($title){
         $sql = parent::checkPost($title);

        return ($sql) && $sql->num_rows > 0;
    }

    /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function getPost($id = '',$limit = ''){
        $user = parent::getPost($id,$limit);
        $data = false;

        if($user->num_rows > 0)
            if(!empty($id))
                $data = $user->fetch_object();
            else
                $data = $user->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

    /**
     * @param $user
     * @param string $limit
     * @return mixed
     */
    public function get_post_by_user($user,$limit = '')
    {
        $sql = parent::get_post_by_user($user, $limit); // TODO: Change the autogenerated stub

        $data = false;

        if($sql->num_rows > 0)
            $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

    /**
     * @param $data
     * @return false|mixed
     */
    public function update_post($data)
    {
        return parent::update_post($data);
    }

    /**
     * @param $id
     * @param $user_id
     * @return bool
     */
    public function deletePost($id, $user_id)
    {
        return (parent::deletePost($id,$user_id)->num_rows > 0);
    }

}