<?php

include_once $_SERVER["DOCUMENT_ROOT"]."/api/v1/Module/TipsModule.php";

class TipController extends TipsModule
{

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @param $data
     * @return false
     */
    public function addTip($data){
        return parent::addTip($data);
    }

    /**
     * @param $title
     * @return bool
     */
    public function checkTip($title){
         $sql = parent::checkTip($title);

        return ($sql) && $sql->num_rows > 0;
    }

    /**
     * @param string $id
     * @param string $category
     * @param bool $not
     * @param string $limit
     * @return array
     */
    public function getPost($id = '',$limit = ''){
        $sql = parent::getTip($id,$limit);
        $data = false;

        if($sql->num_rows > 0)
            if(!empty($id))
                $data = $sql->fetch_object();
            else
                $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

    /**
     * @param $user
     * @param string $limit
     * @return mixed
     */
    public function get_tip_by_user($user,$limit = '')
    {
        $sql = parent::get_tip_by_user($user, $limit); // TODO: Change the autogenerated stub

        $data = false;

        if($sql->num_rows > 0)
            $data = $sql->fetch_all(MYSQLI_ASSOC);

        return $data;
    }

    /**
     * @param $data
     * @return false|mixed
     */
    public function update_tip($data)
    {
        return parent::update_tip($data);
    }

    /**
     * @param $id
     * @param $user_id
     * @return bool
     */
    public function deleteTip($id, $user_id)
    {
        return (parent::deleteTip($id,$user_id)->num_rows > 0);
    }

}