<?php


include_once __DIR__."/../Module/Database.php";

class PaymentModal extends Database
{
	public $table = "subscription";

    public function __construct()
    {
        parent::__construct();
    }

    public function add($obj){
        $data =(array)  parent::decode($obj);

        $status = false;
        $d = '';
        if(count($data) > 0) {

            foreach ($data as $key => $value) {
                if (!empty($value))
                    $d .= "$key='$value',";
            }
            $d = chop($d,',');

            $d .= "created_at=NOW()";

            $status = $this->insert($this->encode(['table'=>$this->table,
                'data'=>$d]));
            if($status)
                $status = $this->con->insert_id;
        }

        print_r($this->con->error);
        return $status;
    }

    public function updatePayment($data){
        $data = (array) parent::decode($data);
        $status = false;
        $d = '';
        if(count($data) > 0){

            foreach ($data as $key=>$value) {
                if(!empty($value) && $key !== 'id' && $key !== 'token' )
                    $d .= "$key='$value',";
            }

            $d = chop($d,',');
            $d .= "paid_at =NOW()";

            $id = $data['id'];
            $token = $data['token'];

            $status = parent::update(parent::encode(array("table"=>$this->table,"data"=>$d, "where"=>"token='$token' AND id='$id'")));
        }

        return $status;
    }

    public function exist($order_id,$token){
        $where = !empty($order_id) && !empty($token) ? "WHERE id='$order_id' AND token='$token'" : '';
		
        return parent::query($this->encode(['query'=>"SELECT id FROM $this->table $where"])) ;
    }

    public function delete($id)
    {
        return parent::delete($this->encode(['table'=>$this->table, 'data'=>"id='$id'"])); // TODO: Change the autogenerated stub
    }

    public function get($id = ''){
        $where = !empty($id) ? "WHERE phone='$id'" : '';
        //$where = !empty($id) && !is_numeric($id) ? "WHERE phone='$id'" : '';
        $sql = "SELECT * FROM $this->table $where ORDER BY id DESC ";

//        echo $sql;
        return parent::query($this->encode(['query'=>$sql])) ;
    }

}